---
# tasks file for join-masters
- name: Debug
  ansible.builtin.debug:
    msg: "[MASTER] K8S_TOKEN_MASTER - O token eh {{ hostvars['K8S_TOKEN_MASTER']['command'] }}"

# - name: Removendo o cluster
#   command:
#     kubeadm reset --force
#   register: kubeadm_reset

- name: Adicionando master ao cluster k8s
  ansible.builtin.command:
    cmd: "{{ hostvars['K8S_TOKEN_MASTER']['command'] }}"

- name: Registrando token em arquivo
  ansible.builtin.lineinfile:
    dest: "./token"
    line: "{{ hostvars['K8S_TOKEN_MASTER']['command'] }}"
    create: yes
    owner: "{{ user_run }}"
    group: "{{ user_run }}"
    mode: '0644'
  become: true

- name: Criando o diretório .kube
  ansible.builtin.file:
    path: /root/.kube
    state: directory
    mode: '0755'

- name: Linkando o arquivo admin.conf para o ~/.kube/config
  ansible.builtin.file:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    state: link
