- name: Verificar se a linha de swap existe no fstab
  ansible.builtin.command:
    cmd: awk '/swap/ {print $1}' /etc/fstab
  register: swapLine

- name: Comentando a linha de SWAP no fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: '^{{ swapLine.stdout }}'
    line: '#{{ swapLine.stdout }}'
    state: present
  when: swapLine.stdout != '' and '#' not in swapLine.stdout

- name: Configurar módulos para Kubernetes
  ansible.builtin.copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      br_netfilter

- name: Configurar parametros sysctl para Kubernetes
  ansible.builtin.copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1

- name: Aplicar configurações sysctl e desabilitar swap
  block:
    - name: Aplicar configurações sysctl
      ansible.builtin.command: sysctl --system

    - name: Desabilitar swap
      ansible.builtin.command: swapoff -a
