---
# tasks file for create-cluster

- name: Inicializando o cluster k8s
  ansible.builtin.command:
    cmd: kubeadm init --control-plane-endpoint {{ control_plane_url }} --upload-certs --pod-network-cidr={{ kubernetes_pod_network_cidr }} --service-cidr={{ kubernetes_service_cidr }}
  register: kubeadm_init
  changed_when: '"initialized successfully" in kubeadm_init.stdout'

- name: Criando o diretório .kube
  ansible.builtin.file:
    path: /root/.kube
    state: directory
    mode: '0755'

- name: Linkando o arquivo admin.conf para o ~/.kube/config
  ansible.builtin.file:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    state: link

- name: Adicionando Calico
  ansible.builtin.copy:
    src: calico-operator.yaml
    dest: /tmp/calico-operator.yaml

- name: Criando Calico Operator
  ansible.builtin.command:
    cmd: kubectl create -f /tmp/calico-operator.yaml
  register: calico_result

- name: Adicionando Configuracoes Calico
  ansible.builtin.copy:
    src: calico-custom-resources.yaml
    dest: /tmp/calico-custom-resources.yaml

- name: Aplicando configurações Calico Operator
  ansible.builtin.command:
    cmd: kubectl create -f /tmp/calico-custom-resources.yaml
  register: calico_result_config
